baseURL = "https://cqroot.github.io/"
languageCode = "en-us"
title = "Keith Chu's Blog"

[module]
[[module.imports]]
path = "github.com/alex-shpak/hugo-book"

[params]
BookTheme = "auto"
BookToC = true

[caches]
[caches.images]
dir = ":cacheDir/images"
