baseURL = "https://cqroot.github.io/"
languageCode = "en-us"
title = "KEITH'S BLOG"

[module]
[[module.imports]]
path = "github.com/alex-shpak/hugo-book"

[params]
BookTheme = "auto"
BookToC = true

[caches]
[caches.images]
dir = ":cacheDir/images"

[menu]
[[menu.after]]
name = "GitHub"
url = "https://github.com/cqroot"
weight = 10
